# пример запуска скрипта docker compose -f docker-compose.prod.yml -p nextjs-prod up
services:
  nextjs-prod:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile.prod
    container_name: prod-mod
    restart: always
    ports:
      - "3000:3000"
    # environment:
    #   NODE_ENV: production