# пример запуска скрипта docker compose -f docker-compose.dev.yml -p nextjs-dev up

services:
  nextjs-dev:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile.dev
    container_name: dev-mod
    ports:
      - '4000:4000'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:4000 || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
